### PR TITLE
Implement Polymorphism for Transcoder interconnect

### PR DESCRIPTION
**Pull request by coolacid**
Here's my (assumingly) terrible attempt at implementing polymorphism. 

In theory, this will allow different connection types to be configured in the Transcoder configuration file. 

I've been testing this on a local Raspberry Pi as it sits, but haven't actually started implementing alternative methods as the tcd project doesn't yet implement configurations. 

*Note*

I'm not a C++ coder. I'm more of a python coder, and still trying to remember C, Rust. So, I expect this to be terrible code, but an option to build on.

### CODE REVIEW

**Comment by n7tae** [comment]
Allowing remote transcoder support is a really big job. Here's why. tcd is incredibly simple, especially when compared to its predecessor, ambed. Tcd and urfd rely on absolute certainty that packets moving between the reflector and the transcoder arrive in order and none are missing. I think the only drop-in for your approach is a UDP socket and UDP is too unreliable. I think TCP is the correct choice for tcd/urfd remote comms. This means the first step is to rewrite urfd/tcd using a **single** Unix bidirectional socket with a router in urfd to get the transcoded packet back to the correct CCodecStream object. This needs to be done first.

This would be a good part of the solution, but it's not complete. I don't want to accept this now. In my opinion, it's putting the cart before the horse.

**Comment by n7tae** [comment]
Remote transcoding is now available in the tcp branches of both urfd and tcd. Give it a try, if you have time. Don't be confused by the clone statements in the READMEs, where it is assumed that these branches will be merged with main and pushed upstream to nostar.

**Comment by jaskenda-talos** [comment]
Hey @n7tae thanks for this! I created a node on my server, and transcoded on a rPi at the house and it seems to appear to work. I haven't actually tested across two radio types yet, but I'll get to that I hope later. 

You can either close this, or make use of it to implement both local and TCP based transcode. 

Thanks again for the work you're putting into this.

**Comment by n7tae** [comment]
Thank you @jaskenda-talos ! I have only tested this in my local network at home, so I am very curious about latency. What kind of average transcoding turn-around times are you getting (that's the middle number in the `TC round-trip time(ms)` entries in the reflector log)? How does that compare to ping times between your reflector and transcoder?

**Comment by coolacid** [comment]
@n7tae Stupid work account. Can you edit to change the user? 

Original Comment: 

Hey @n7tae thanks for this! I created a node on my server, and transcoded on a rPi at the house and it seems to appear to work. I haven't actually tested across two radio types yet, but I'll get to that I hope later.

You can either close this, or make use of it to implement both local and TCP based transcode.

Thanks again for the work you're putting into this.

**Comment by coolacid** [comment]
Some quick key-ups gives me the following. 

```
TC round-trip time(ms): 44.8/87.6/175.0, 38 total packets
TC round-trip time(ms): 51.7/107.5/305.8, 101 total packets
TC round-trip time(ms): 53.5/112.0/300.3, 96 total packets
```

About 19 hops listed on a tracepath. For a ping time we're looking at:

```
rtt min/avg/max/mdev = 23.316/30.436/40.913/4.485 ms
```

**Comment by n7tae** [comment]
Okay thanks. Closing this...

**Pull request closed without merging**
