### PR TITLE
Add define for YSF reflector description and optional defines for nam…

### PR DESCRIPTION
**Pull request by nostar**
…e and id.

### CODE REVIEW

**Comment by n7tae** [comment]
I have some questions:
- Are the ID and callsign values something that my ./rconfig script should set?
- Why "XLX" and not "URF"?
- Can you tell me a little more about the ID? To what "registry" are you referring?

**Comment by nostar** [comment]
https://register.ysfreflector.de/ 

The YSF registry is where all hotspots/apps get their YSFHosts list like this one for Pistar:
http://www.pistar.uk/downloads/YSF_Hosts.txt

This registry server is what sends a status request every minute or so, that YSFReflector responds to with that YSFS status packet.  If you do not define an ID, or if the one you chose is in use, the registry assigns one for you.  In the original G4KLX YSFReflector software  the name, description, and ID are all config settings in the ini file.  In XLX and URF, ID is not set and name/description are hard coded to the reflector callsign and 'XLX reflector'.

Why "XLX" and not "URF"?
I think you are asking about the commented out name using XLX000 as an example.  It doesn't matter really, the point is to change it to something more YSF friendly like US-QuadNet for example.  I was going to make the commented example something like US-MyYSF but I forgot. Since it is commented out by default, the reflector callsign would be used.  Description too, I just carried over the current default but it could be URF reflector instead.  

As far as putting them in the rconfig, that's your call. I wonder if you have considered putting the entire Main.h file into the rconfig script.  The reflector ports, for example, would be well served by the rconfig script.

**Comment by n7tae** [comment]
I added name and description to the rconfig script and bumped the version to 0.0.4 and pushed it up. I changed your code a bit. Take a look at YSFProtocol.cpp.

The entire Main.h? Give me a priority. Would ports be the most useful? I would probably break those out into a separate sub-menu so that they would all be together. Does that sound okay?

**Comment by nostar** [comment]
Everything looks good. Ports and the fallback DMRMMDVM_DEFAULTID to use for failed YSF callsign to DMR ID lookups would probably be the most useful.

**Pull request merged**
